// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.TypeOfBehavior_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.ApplyToAttribute_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.StartMin_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.StartMax_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.ChangeMin_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.ChangeMax_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.TotalTimeMin_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.BehaviorSettingTests.TotalTimeMax_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.TypoeOfBehavior_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.ApplyBehaviorTo_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.SpawnLocation_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.TintColors_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.TotalParticlesAliveAtOnce_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.SpawnRateMin_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.SpawnRateMax_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.ParticleEffectTests.UseColorsFromList_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.EasingBehaviorTests.Start_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.EasingBehaviorTests.Value_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.EasingBehaviorTests.TotalTime_WhenSettingValue_ReturnsCorrectValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:KDParticleEngineTests.Behaviors.EasingBehaviorTests.Change_WhenSettingValue_ReturnsCorrectValue")]
