parameters:
- name: engineProjectName
  type: string
- name: engineTesterProjectName
  type: string
- name: buildPlatform
  type: string  
- name: buildConfiguration
  type: string  
- name: vstsFeed
  type: string


jobs:
- job: 'Publish_Particle_Engine_Artifacts_Job' #🟠
  displayName: 'Publish ParticleEngine Artifacts'
  steps:
  - template: setup-nuget-task-template.yml
    parameters:
      projectName: ${{parameters.engineProjectName}}
      vstsFeed: ${{parameters.vstsFeed}}


  - task: CmdLine@2
    displayName: '🟣Create ${{parameters.engineProjectName}} Nuget Package Artifact'
    inputs:
      script: "dotnet pack \"$(System.DefaultWorkingDirectory)\\${{parameters.engineProjectName}}\\${{parameters.engineProjectName}}.csproj\" -c ${{parameters.buildConfiguration}} /p:Platform=${{parameters.buildPlatform}} -o $(Build.ArtifactStagingDirectory)"


  - task: PublishBuildArtifacts@1
    displayName: '🟣Publish ${{parameters.engineProjectName}} Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'




- job: 'Publish_Engine_Tester_Artifacts_Job' #🟠
  displayName: 'Publish ParticleEngineTester Artifacts'
  steps:
  - template: setup-nuget-task-template.yml
    parameters:
      projectName: ${{parameters.engineTesterProjectName}}
      vstsFeed: ${{parameters.vstsFeed}}


  - task: DotNetCoreCLI@2
    displayName: '🟣Publish ${{parameters.engineTesterProjectName}} Artifacts'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(System.DefaultWorkingDirectory)/**/${{parameters.engineTesterProjectName}}.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory) -c ${{parameters.buildConfiguration}} /p:Platform=${{parameters.buildPlatform}}'
      zipAfterPublish: true
      modifyOutputPath: false


  - task: CmdLine@2
    displayName: '🟣Rename ${{parameters.engineTesterProjectName}} Artifact'
    inputs:
      script: 'ren "$(Build.ArtifactStagingDirectory)\a.zip" "${{parameters.engineTesterProjectName}}.zip"'


  - task: CmdLine@2
    displayName: '🟣Copy ${{parameters.engineTesterProjectName}} Project File'
    inputs:
      script: 'copy "$(System.DefaultWorkingDirectory)\${{parameters.engineTesterProjectName}}\${{parameters.engineTesterProjectName}}.csproj" "$(Build.ArtifactStagingDirectory)" /Y'


  - task: PublishBuildArtifacts@1
    displayName: '🟣Publish ${{parameters.engineTesterProjectName}} Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
