trigger:
  branches:
    include:
    - develop # Development Environment
    - master # Production Environment


variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    ${{ if notIn(variables['Build.SourceBranchName'], 'develop', 'master')}}:
      value: 'Debug'
    ${{ if eq(variables['Build.SourceBranchName'], 'develop')}}:
      value: 'Debug'
    ${{ if eq(variables['Build.SourceBranchName'], 'master')}}:
      value: 'Release'
  - name: coverageReportDirName
    value: 'CoverageReport'
  - name: engineProjectName
    value: 'ParticleEngine'
  - name: engineTesterProjectName
    value: 'ParticleEngineTester'
  - name: pool
    value: 'KinsonServer'

stages:
- stage: Print_Variable_Stage
  displayName: Print Variables
  pool: $(pool)
  jobs:
  - job: 'Print_Variables_Job'
    displayName: Print Variables
    steps:
    - task: CmdLine@2
      displayName: Print Variables
      inputs:
        script: |
          echo =====================================================================================
          echo solution: $(solution)
          echo buildPlatform: $(buildPlatform)
          echo buildConfiguration: $(buildConfiguration)
          echo coverageReportDirName: $(coverageReportDirName)
          echo engineProjectName: $(engineProjectName)
          echo engineTesterProjectName: $(engineTesterProjectName)
          echo pool: $(pool)
          echo =====================================================================================


- stage: Build_Stage
  displayName: 'Build Stage'
  pool: '$(pool)'
  jobs:
  - template: templates/build-content-job-template.yml
    parameters:
      engineTesterProjectName: $(engineTesterProjectName)
      monoToolDirName: MGCB
      contentFileName: Content.mgcb

  - template: templates/build-solution-job-template.yml
    parameters:
      engineProjectName: $(engineProjectName)
      engineTesterProjectName: $(engineTesterProjectName)
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '1020f331-f22a-4330-a69a-78abfe6f6372/4c644bf2-f1e8-4f28-a3df-3bc9d3283df9' # KinsonDigitalFeed


- stage: Testing_Stage
  displayName: 'Testing Stage'
  pool: '$(pool)'
  dependsOn: 'Build_Stage'
  jobs:
  - template: templates/unit-testing-job-template.yml
    parameters:
      engineProjectName: $(engineProjectName)
      engineTesterProjectName: $(engineTesterProjectName)
      buildConfiguration: $(buildConfiguration)
      coverageReportDirName: $(coverageReportDirName)


- stage: Publish_Artifacts_Stage
  displayName: 'Publish Artifacts Stage'
  pool: '$(pool)'
  dependsOn: 'Testing_Stage'
  jobs:
  - template: templates/publish-artifacts-job-template.yml
    parameters:
      engineProjectName: $(engineProjectName)
      engineTesterProjectName: $(engineTesterProjectName)
