trigger:
  branches:
    include:
    - develop # Development Environment
    - master # Production Environment


variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'any'
- name: buildConfiguration
  ${{ if notIn(variables['Build.SourceBranchName'], 'develop', 'master')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop')}}:
    value: 'Debug'
  ${{ if eq(variables['Build.SourceBranchName'], 'master')}}:
    value: 'Release'
- name: engineProjectName
  value: 'ParticleEngine'
- name: engineTesterProjectName
  value: 'ParticleEngineTester'
- name: kinsonDigitalNugetFeed
  value: '1020f331-f22a-4330-a69a-78abfe6f6372/4c644bf2-f1e8-4f28-a3df-3bc9d3283df9'    
- name: pool
  value: 'KinsonServer'


stages:
- stage: Print_Variable_Stage #🟢
  displayName: Print Variables
  pool: $(pool)
  jobs:
  - job: 'Print_Variables_Job' #🟠
    displayName: Print Variables
    steps:
    - task: PowerShell@2
      displayName: Print Variables
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##[group]Pipeline Variables"
          Write-Host "##[command]solution: $(solution)"
          Write-Host "##[command]buildPlatform: $(buildPlatform)"
          Write-Host "##[command]buildConfiguration: $(buildConfiguration)"
          Write-Host "##[command]engineProjectName: $(engineProjectName)"
          Write-Host "##[command]engineTesterProjectName: $(engineTesterProjectName)"
          Write-Host "##[command]pool: $(pool)"
          Write-Host "##[endgroup]"




- stage: Build_Stage #🟢
  displayName: 'Build Stage'
  pool: '$(pool)'
  jobs:
  - template: templates/build-content-job-template.yml
    parameters:
      projectName: $(engineTesterProjectName)
      monoToolDirName: MGCB
      contentFileName: Content.mgcb



  - template: templates/build-solution-job-template.yml
    parameters:
      engineProjectName: $(engineProjectName)
      engineTesterProjectName: $(engineTesterProjectName)
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '$(kinsonDigitalNugetFeed)'




- stage: Testing_Stage #🟢
  displayName: 'Testing Stage'
  pool: '$(pool)'
  jobs:
  - template: templates/unit-testing-job-template.yml
    parameters:
      engineProjectName: $(engineProjectName)
      engineTesterProjectName: $(engineTesterProjectName)
      buildPlatform: $(buildPlatform)      
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '$(kinsonDigitalNugetFeed)'




- stage: Publish_Artifacts_Stage #🟢
  displayName: 'Publish Artifacts Stage'
  pool: '$(pool)'
  condition: in(variables['Build.SourceBranchName'], 'develop', 'master')
  jobs:
  - template: templates/publish-artifacts-job-template.yml
    parameters:
      engineProjectName: $(engineProjectName)
      engineTesterProjectName: $(engineTesterProjectName)
      buildPlatform: $(buildPlatform)
      buildConfiguration: $(buildConfiguration)
      vstsFeed: '$(kinsonDigitalNugetFeed)'
